name: Loungebird
description: LHR Lounges at your fingertips. Coming Soon.
full_description: 'Loungebird is the ultimate companion to experiencing lounges at London Heathrow Terminal 5<br>
<br>Featuring:
<br>- Live streaming of occupancy data directly from the lounges.
<br>- Support for Home and Lock Screen widgets.
<br>- And much more...
<br>
Coming soon to iOS, iPadOS and macOS'
#iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
