name: Loungebird
description: Lounge smarter at London Heathrow.
full_description: 'Loungebird is the perfect companion for relaxing at the lounges before your flight from London Heathrow Terminal 5.<br>
<br>Featuring:<br>
<br>- A beautiful, customisable design.
<br>- Live streaming of occupancy data directly from the lounges.
<br>- Glanceable Home and Lock Screen widgets.
<br>- And much more.
<br>
<br>Coming soon to iPhone, iPad and Mac.'
iOS: https://apps.apple.com/app/id6473727770
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
